#!/usr/bin/env bash

VERSION=$(grep '^version' Cargo.toml | head -1 | awk -F'"' '{print $2}')
ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')

rm -rf /tmp/release
mkdir -p /tmp/release
cp target/release/pod-babashka-filewatcher /tmp/release

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-filewatcher-$VERSION-$PLATFORM-$ARCH.zip" pod-babashka-filewatcher

## cleanup

rm pod-babashka-filewatcher
